import type { Method, SystemInput } from "../api/types";

export const METHODS: Record<Method, { name: string; category: string; description: string; benefit: string; limitation: string }> = {
  gaussian: { name: "Gaussian elimination", category: "Direct", description: "Reduces your matrix to row-echelon form with partial pivoting, then solves by back-substitution.", benefit: "Advantages: deterministic, finishes in a bounded number of steps, works on rectangular systems.", limitation: "Limitations: doesn't directly hand you reduced form — Gauss–Jordan goes one step further if you want that." },
  gauss_jordan: { name: "Gauss–Jordan elimination", category: "Direct", description: "Continues elimination to reduced row-echelon form, reading solutions (including parametric families) directly off the result.", benefit: "Advantages: the clearest path to a full solution set, including infinite-solution cases.", limitation: "Limitations: more row operations than Gaussian elimination for the same system — a small cost for the extra clarity." },
  jacobi: { name: "Jacobi iteration", category: "Iterative", description: "Refines an initial guess using only the previous iteration's values, updated all at once each sweep.", benefit: "Advantages: simple, easy to parallelize conceptually, a good baseline for comparing convergence behavior.", limitation: "Limitations: requires a square system; convergence isn't guaranteed and depends on the iteration matrix's spectral radius." },
  gauss_seidel: { name: "Gauss–Seidel iteration", category: "Iterative", description: "Refines an initial guess using the newest values already computed within the same sweep.", benefit: "Advantages: typically converges in fewer iterations than Jacobi when both converge.", limitation: "Limitations: same square-system requirement; still not guaranteed to converge for every matrix." },
};
export const PRESETS: { id: string; name: string; note: string; system: SystemInput; method: Method; reorder?: boolean }[] = [
  { id: "planes", name: "3D · three planes meet", note: "Three independent planes meet at (1, 2, 3).", system: { a: [["4", "1", "0"], ["1", "4", "1"], ["0", "1", "4"]], b: ["6", "12", "14"] }, method: "gauss_jordan" },
  { id: "line3d", name: "3D · a line of solutions", note: "Two independent constraints leave a line of common intersections.", system: { a: [["1", "1", "0"], ["0", "1", "1"], ["1", "2", "1"]], b: ["2", "3", "5"] }, method: "gauss_jordan" },
  { id: "coincident", name: "2D · coincident lines", note: "Both equations describe the same line; every point on it is a solution.", system: { a: [["1", "1"], ["2", "2"]], b: ["2", "4"] }, method: "gauss_jordan" },
  { id: "unique", name: "Unique · a gentle start", note: "Two independent equations; the solution is x₁ = 0.1, x₂ = 0.6.", system: { a: [["4", "1"], ["2", "3"]], b: ["1", "2"] }, method: "gaussian" },
  { id: "infinite", name: "Infinite · a free variable", note: "Two equations, three unknowns. Explore a family of solutions.", system: { a: [["1", "1", "1"], ["0", "1", "2"]], b: ["3", "4"] }, method: "gauss_jordan" },
  { id: "inconsistent", name: "Inconsistent · a contradiction", note: "The same left side cannot equal both 2 and 3.", system: { a: [["1", "1"], ["1", "1"]], b: ["2", "3"] }, method: "gauss_jordan" },
  { id: "ill", name: "Ill-conditioned · close equations", note: "Nearly dependent rows amplify input changes. Compare float and exact modes.", system: { a: [["1", "1"], ["1", "1.0000000001"]], b: ["2", "2.0000000001"] }, method: "gaussian" },
  { id: "permutation", name: "Reordering · recover the diagonal", note: "Swap the equations to obtain a safe, strictly dominant diagonal.", system: { a: [["0", "4"], ["3", "1"]], b: ["8", "5"] }, method: "jacobi" },
  { id: "divergent", name: "Non-convergent · inspect the risk", note: "With reordering off and a zero start, this iteration diverges. An explicit risk override is required to run it.", system: { a: [["1", "2"], ["2", "1"]], b: ["1", "1"] }, method: "jacobi", reorder: false },
];
