import Link from "next/link";
import { SiteHeader } from "../../components/site-header";
import { METHODS } from "../../lib/solver/presets";

export default function LearnPage() {
  return <main id="main" className="page-shell"><SiteHeader /><section className="intro"><p className="eyebrow">A short field guide</p><h1>More than<br /><span>an answer.</span></h1><p className="lead">A system of equations describes constraints on the same unknowns. Solving it means finding the values that satisfy every equation together.</p><Link href="/solve" className="primary-link">Open the solver ↗</Link></section>
    <section className="panel"><h2>Three possible outcomes</h2><dl className="learn-definitions"><dt>Unique</dt><dd>The coefficient and augmented ranks equal the number of unknowns. Every variable is determined.</dd><dt>Infinite</dt><dd>The ranks agree but leave free variables. Parameters describe the whole solution family.</dd><dt>Inconsistent</dt><dd>The augmented rank exceeds the coefficient rank. Row reduction exposes a contradiction.</dd></dl><p>Rectangular systems are welcome in direct methods. Shape alone does not determine consistency.</p></section>
    <section className="method-grid learn-methods">{Object.entries(METHODS).map(([key, method]) => <article className="glass-panel" key={key}><p className="eyebrow">{method.category}</p><h2>{method.name}</h2><p>{method.description}</p><p>{method.benefit}</p><p>{method.limitation}</p></article>)}</section>
    <section className="panel"><h2>Trust the diagnostics, not the number of digits</h2><p>Exact direct arithmetic uses rational numbers. Float64 represents numbers approximately; display rounding never changes the stored calculation.</p><p>The residual measures how closely a candidate satisfies the original equations. Backward error normalizes that residual by the sizes of A, x, and b. Iteration converges only when backward error and normalized step change both meet your tolerance.</p><p>Strict diagonal dominance is sufficient for Jacobi and Gauss–Seidel convergence, but it is not necessary. SPD matrices give a sufficient condition for Gauss–Seidel; SPD alone does not guarantee Jacobi convergence. A method’s spectral radius below one predicts convergence from every initial guess in exact iteration arithmetic.</p><p>A large condition number signals sensitivity to changes in input. Approximate digit loss is an educational diagnostic, not an error bound.</p></section><footer>Try the curated presets to see each idea in action.</footer></main>;
}
