/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report process health without claiming solver readiness.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze System
         * @description Classify a system and explain conditional eligibility for all four methods.
         */
        post: operations["analyze_system"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve System
         * @description Return full results, including mathematical non-success outcomes at HTTP 200.
         */
        post: operations["solve_system"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeOutcome: components["schemas"]["AnalyzeResponse"] | components["schemas"]["NumericalFailure"];
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Arithmetic Mode
             * @default float64
             * @enum {string}
             */
            arithmetic_mode: "float64" | "exact";
            system: components["schemas"]["SystemInput"];
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            classification: components["schemas"]["ClassificationResult"];
            conditioning: components["schemas"]["ConditionDiagnostic"];
            /**
             * Conditioning Arithmetic Mode
             * @default float64
             * @constant
             */
            conditioning_arithmetic_mode: "float64";
            dominance_permutation: components["schemas"]["RowPermutation"] | null;
            /** Is Square */
            is_square: boolean;
            /** Methods */
            methods: components["schemas"]["MethodEligibility"][];
            nonzero_permutation: components["schemas"]["RowPermutation"] | null;
            /** Request Id */
            request_id: string;
            shape: components["schemas"]["SystemShape"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "analyzed";
            /** Strict Diagonal Dominance */
            strict_diagonal_dominance: boolean | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /**
         * ArithmeticMode
         * @enum {string}
         */
        ArithmeticMode: "float64" | "exact";
        /**
         * ClassificationKind
         * @enum {string}
         */
        ClassificationKind: "unique" | "infinite" | "inconsistent";
        /** ClassificationResult */
        ClassificationResult: {
            arithmetic_mode: components["schemas"]["ArithmeticMode"];
            classification: components["schemas"]["ClassificationKind"];
            /** Rank A */
            rank_a: number;
            /** Rank Augmented */
            rank_augmented: number;
            /** Rank Tolerance */
            rank_tolerance: number | null;
            shape: components["schemas"]["SystemShape"];
            /** Tolerance Policy */
            tolerance_policy: string;
        };
        /** ConditionDiagnostic */
        ConditionDiagnostic: {
            approximate_digit_loss?: components["schemas"]["NonnegativeFloat"] | null;
            condition_number?: components["schemas"]["NonnegativeFloat"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "finite" | "singular" | "unavailable";
        };
        /** ConvergenceDiagnostics */
        ConvergenceDiagnostics: {
            /**
             * Assessment
             * @enum {string}
             */
            assessment: "sufficient_condition" | "spectral_radius_below_one" | "convergence_risk";
            /** Explanation */
            explanation: string;
            method: components["schemas"]["IterativeMethod"];
            spectral: components["schemas"]["SpectralDiagnostic"];
            /** Strict Diagonal Dominance */
            strict_diagonal_dominance: boolean;
            /** Symmetric Positive Definite */
            symmetric_positive_definite: boolean | null;
            symmetry_tolerance: components["schemas"]["NonnegativeFloat"];
            /** Weak Diagonal Dominance */
            weak_diagonal_dominance: boolean;
        };
        /**
         * DirectDiagnostics
         * @description Measured on the original system and the returned solution/particular point.
         */
        DirectDiagnostics: {
            backward_error: components["schemas"]["NumericValue"];
            residual_inf: components["schemas"]["NumericValue"];
        };
        /** DirectOptions */
        DirectOptions: {
            /**
             * Arithmetic Mode
             * @default float64
             * @enum {string}
             */
            arithmetic_mode: "float64" | "exact";
        };
        /** DirectResult */
        DirectResult: {
            arithmetic_mode: components["schemas"]["ArithmeticMode"];
            /** Augmented Pivot Columns */
            augmented_pivot_columns: number[];
            classification: components["schemas"]["ClassificationResult"];
            /** Contradictory Rows */
            contradictory_rows: number[];
            diagnostics: components["schemas"]["DirectDiagnostics"] | null;
            /**
             * Form
             * @enum {string}
             */
            form: "ref" | "rref";
            /** Free Columns */
            free_columns: number[];
            matrix: components["schemas"]["NumericMatrix"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "gauss_jordan" | "gaussian";
            parametric_solution: components["schemas"]["ParametricSolution"] | null;
            /** Pivot Columns */
            pivot_columns: number[];
            /** Row Tolerances */
            row_tolerances: number[] | null;
            solution: components["schemas"]["NumericVector"] | null;
            /** Trace */
            trace: components["schemas"]["RowOperation"][];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** DirectSolveRequest */
        DirectSolveRequest: {
            display?: components["schemas"]["DisplayPreferences"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "gauss_jordan" | "gaussian";
            options?: components["schemas"]["DirectOptions"];
            system: components["schemas"]["SystemInput"];
        };
        /** DisplayPreferences */
        DisplayPreferences: {
            /**
             * Decimal Places
             * @default 6
             */
            decimal_places: number;
            /**
             * Mode
             * @default decimal
             * @enum {string}
             */
            mode: "decimal" | "fraction";
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["Issue"][];
            error: components["schemas"]["Issue"];
            /** Request Id */
            request_id: string;
            /**
             * Status
             * @default error
             * @constant
             */
            status: "error";
        };
        ExactScalar: components["schemas"]["RationalValue"];
        /**
         * ExactSystem
         * @description Exact coefficients with bounded integer growth and structured JSON output.
         */
        ExactSystem: {
            /** A */
            a: components["schemas"]["ExactScalar"][][];
            /** B */
            b: components["schemas"]["ExactScalar"][];
        };
        FloatScalar: number;
        /**
         * FloatSystem
         * @description Finite binary64 coefficients and RHS; no rounding or mutable arrays.
         */
        FloatSystem: {
            /** A */
            a: components["schemas"]["FloatScalar"][][];
            /** B */
            b: components["schemas"]["FloatScalar"][];
        };
        /**
         * HealthResponse
         * @description Health describes the API process, not numerical feature availability.
         */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        InputRow: components["schemas"]["NumericToken"][];
        /** Issue */
        Issue: {
            /** Code */
            code: string;
            /**
             * Location
             * @default []
             */
            location: (string | number)[];
            /** Message */
            message: string;
        };
        /** IterationMetrics */
        IterationMetrics: {
            backward_error: components["schemas"]["NonnegativeFloat"];
            residual_inf: components["schemas"]["NonnegativeFloat"];
        };
        /** IterationOptions */
        IterationOptions: {
            /**
             * Auto Reorder For Diagonal Dominance
             * @default true
             */
            auto_reorder_for_diagonal_dominance: boolean;
            /**
             * Auto Reorder For Nonzero Diagonal
             * @default false
             */
            auto_reorder_for_nonzero_diagonal: boolean;
            /** Initial Guess */
            initial_guess?: components["schemas"]["FloatScalar"][] | null;
            /**
             * Max Iterations
             * @default 25
             */
            max_iterations: number;
            /**
             * Run Despite Convergence Risk
             * @default false
             */
            run_despite_convergence_risk: boolean;
            /**
             * Tolerance
             * @default 1e-8
             */
            tolerance: number;
        };
        /** IterationRecord */
        IterationRecord: {
            backward_error: components["schemas"]["NonnegativeFloat"];
            /** Converged */
            converged: boolean;
            delta_inf: components["schemas"]["NonnegativeFloat"];
            /** Index */
            index: number;
            normalized_step_change: components["schemas"]["NonnegativeFloat"];
            residual_inf: components["schemas"]["NonnegativeFloat"];
            vector: components["schemas"]["solver_core__models__FloatVector__2"];
        };
        /**
         * IterationStatus
         * @enum {string}
         */
        IterationStatus: "converged" | "max_iterations_reached" | "numeric_breakdown" | "convergence_risk_declined";
        /** @enum {string} */
        IterativeMethod: "jacobi" | "gauss_seidel";
        /** IterativeOptions */
        IterativeOptions: {
            /**
             * Auto Reorder For Diagonal Dominance
             * @default true
             */
            auto_reorder_for_diagonal_dominance: boolean;
            /**
             * Auto Reorder For Nonzero Diagonal
             * @default false
             */
            auto_reorder_for_nonzero_diagonal: boolean;
            /** Initial Guess */
            initial_guess?: components["schemas"]["NumericToken"][] | null;
            /**
             * Max Iterations
             * @default 25
             */
            max_iterations: number;
            /**
             * Run Despite Convergence Risk
             * @default false
             */
            run_despite_convergence_risk: boolean;
            /**
             * Tolerance
             * @default 1e-8
             */
            tolerance: number;
        };
        /** IterativeResult */
        IterativeResult: {
            /**
             * Arithmetic Mode
             * @default float64
             * @constant
             */
            arithmetic_mode: "float64";
            /** Breakdown Reason */
            breakdown_reason?: string | null;
            classification: components["schemas"]["ClassificationResult"];
            conditioning: components["schemas"]["ConditionDiagnostic"];
            convergence: components["schemas"]["ConvergenceDiagnostics"];
            diagnostics: components["schemas"]["IterationMetrics"] | null;
            /** History */
            history: components["schemas"]["IterationRecord"][];
            initial_guess: components["schemas"]["solver_core__models__FloatVector__1"];
            last_iterate: components["schemas"]["solver_core__models__FloatVector__1"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "gauss_seidel" | "jacobi";
            options: components["schemas"]["IterationOptions"];
            reordering: components["schemas"]["ReorderingDiagnostics"];
            solution: components["schemas"]["solver_core__models__FloatVector__1"] | null;
            status: components["schemas"]["IterationStatus"];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** IterativeSolveRequest */
        IterativeSolveRequest: {
            display?: components["schemas"]["DisplayPreferences"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "gauss_seidel" | "jacobi";
            options?: components["schemas"]["IterativeOptions"];
            system: components["schemas"]["SystemInput"];
        };
        /** @enum {string} */
        Method: "gaussian" | "gauss_jordan" | "jacobi" | "gauss_seidel";
        /**
         * MethodEligibility
         * @description Eligible means available subject to the stated reordering and risk requirements.
         */
        MethodEligibility: {
            /**
             * Code
             * @enum {string}
             */
            code: "available" | "requires_square" | "requires_unique" | "requires_float64" | "unsafe_diagonal" | "requires_row_reordering" | "convergence_risk" | "numeric_breakdown";
            convergence: components["schemas"]["ConvergenceDiagnostics"] | null;
            /** Eligible */
            eligible: boolean;
            method: components["schemas"]["Method"];
            /** Reason */
            reason: string;
            /**
             * Requires Risk Override
             * @default false
             */
            requires_risk_override: boolean;
            /**
             * Requires Row Reordering
             * @default false
             */
            requires_row_reordering: boolean;
            row_permutation: components["schemas"]["RowPermutation"] | null;
        };
        NonnegativeFloat: components["schemas"]["FloatScalar"];
        NumericMatrix: components["schemas"]["NumericVector"][];
        NumericToken: string;
        NumericValue: components["schemas"]["ExactScalar"] | components["schemas"]["FloatScalar"];
        NumericVector: components["schemas"]["NumericValue"][];
        /**
         * NumericalFailure
         * @description A controlled numerical limitation, without an invented classification or solution.
         */
        NumericalFailure: {
            arithmetic_mode: components["schemas"]["ArithmeticMode"];
            error: components["schemas"]["Issue"];
            method: components["schemas"]["Method"] | null;
            /** Request Id */
            request_id: string;
            shape: components["schemas"]["SystemShape"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "numeric_breakdown";
        };
        /** ParameterTerm */
        ParameterTerm: {
            coefficient: components["schemas"]["NumericValue"];
            /** Parameter */
            parameter: string;
        };
        /** ParametricSolution */
        ParametricSolution: {
            /** Expressions */
            expressions: components["schemas"]["VariableExpression"][];
            /** Free Variables */
            free_variables: number[];
            /** Pivot Variables */
            pivot_variables: number[];
        };
        /** ProblemMetadata */
        ProblemMetadata: {
            arithmetic_mode: components["schemas"]["ArithmeticMode"];
            /** Is Square */
            is_square: boolean;
            /** Original System */
            original_system: components["schemas"]["FloatSystem"] | components["schemas"]["ExactSystem"];
            shape: components["schemas"]["SystemShape"];
        };
        /**
         * RationalValue
         * @description Canonical exact rational; JSON integers are strings to prevent JS loss.
         */
        RationalValue: {
            /** Denominator */
            denominator: string;
            /** Numerator */
            numerator: string;
        };
        /** ReorderingDiagnostics */
        ReorderingDiagnostics: {
            /** Dominance Matching Found */
            dominance_matching_found: boolean | null;
            /** Dominance Search Attempted */
            dominance_search_attempted: boolean;
            /** Nonzero Search Attempted */
            nonzero_search_attempted: boolean;
            permutation: components["schemas"]["RowPermutation"];
        };
        /**
         * ReportMetadata
         * @description Use problem + result + this metadata; traces are never duplicated.
         */
        ReportMetadata: {
            display: components["schemas"]["DisplayPreferences"];
            /**
             * Fraction Values
             * @enum {string}
             */
            fraction_values: "exact" | "approximate";
            method: components["schemas"]["Method"];
            /** Options */
            options: components["schemas"]["DirectOptions"] | components["schemas"]["IterativeOptions"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Solver Version
             * @default 0.1.0
             * @constant
             */
            solver_version: "0.1.0";
        };
        /** RowOperation */
        RowOperation: {
            /** Explanation */
            explanation: string;
            factor: components["schemas"]["NumericValue"] | null;
            /** Index */
            index: number;
            matrix_after: components["schemas"]["NumericMatrix"];
            /**
             * Operation Type
             * @enum {string}
             */
            operation_type: "row_swap" | "row_add_scaled" | "row_scale";
            /**
             * Phase
             * @enum {string}
             */
            phase: "forward_elimination" | "backward_elimination";
            /** Pivot Column */
            pivot_column: number;
            /** Source Row */
            source_row: number | null;
            /** Target Row */
            target_row: number;
        };
        /**
         * RowPermutation
         * @description order[j] is the original equation moved to row j; variables never move.
         */
        RowPermutation: {
            /** Order */
            order: number[];
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "identity" | "strict_diagonal_dominance" | "nonzero_diagonal";
        };
        SolveOutcome: components["schemas"]["SolveResponse"] | components["schemas"]["NumericalFailure"];
        /**
         * SolveResponse
         * @description Completed means the computation returned a result, not that it converged.
         *
         *     Inspect result.classification for direct methods and result.status for iteration.
         *     Conditioning always estimates the original coefficient matrix in float64.
         */
        SolveResponse: {
            conditioning: components["schemas"]["ConditionDiagnostic"];
            /**
             * Conditioning Arithmetic Mode
             * @default float64
             * @constant
             */
            conditioning_arithmetic_mode: "float64";
            problem: components["schemas"]["ProblemMetadata"];
            report: components["schemas"]["ReportMetadata"];
            /** Request Id */
            request_id: string;
            /** Result */
            result: components["schemas"]["DirectResult"] | components["schemas"]["IterativeResult"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "completed";
        };
        /** SpectralDiagnostic */
        SpectralDiagnostic: {
            radius?: components["schemas"]["NonnegativeFloat"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "computed" | "unavailable";
        };
        /** SystemInput */
        SystemInput: {
            /** A */
            a: components["schemas"]["InputRow"][];
            /** B */
            b: components["schemas"]["NumericToken"][];
        };
        /** SystemShape */
        SystemShape: {
            /** Equations */
            equations: number;
            /** Unknowns */
            unknowns: number;
        };
        /** VariableExpression */
        VariableExpression: {
            constant: components["schemas"]["NumericValue"];
            /** Terms */
            terms: components["schemas"]["ParameterTerm"][];
            /** Variable */
            variable: string;
        };
        solver_core__models__FloatVector__1: components["schemas"]["FloatScalar"][];
        solver_core__models__FloatVector__2: components["schemas"]["FloatScalar"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID (1–64 ASCII letters, digits, '-' or '_'). Invalid values are replaced; the final ID is returned in X-Request-ID. */
                "x-request-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Invalid input or resource-policy violation. */
            422: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected internal error with correlation ID. */
            500: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyze_system: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID (1–64 ASCII letters, digits, '-' or '_'). Invalid values are replaced; the final ID is returned in X-Request-ID. */
                "x-request-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeOutcome"];
                };
            };
            /** @description Invalid input or resource-policy violation. */
            422: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected internal error with correlation ID. */
            500: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    solve_system: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID (1–64 ASCII letters, digits, '-' or '_'). Invalid values are replaced; the final ID is returned in X-Request-ID. */
                "x-request-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectSolveRequest"] | components["schemas"]["IterativeSolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveOutcome"];
                };
            };
            /** @description Invalid input or resource-policy violation. */
            422: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected internal error with correlation ID. */
            500: {
                headers: {
                    /** @description Request correlation ID. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
